[main]
font=monospace:size=10
dpi-aware=yes

[colors]
background=282828
foreground=ebdbb2

## Normal colors
regular0=282828  # Black
regular1=fb4934  # Red
regular2=49CA94  # Green (Gradiente 4 medio)
regular3=D8F8B0  # Yellow (Gradiente 4 amarillo-verde)
regular4=458588  # Blue (Gruvbox azul oscuro)
regular5=b16286  # Magenta (Gruvbox púrpura oscuro)
regular6=71DDA0  # Cyan (Gradiente 4 aqua)
regular7=ebdbb2  # White

## Bright colors
bright0=504945   # Bright Black (gris medio)
bright1=fb4934   # Bright Red (mismo, ya vibrante)
bright2=A4ECA8   # Bright Green (Gradiente 4 menta)
bright3=fabd2f   # Bright Yellow (Gruvbox dorado)
bright4=83a598   # Bright Blue (Gruvbox azul claro)
bright5=d3869b   # Bright Magenta (Gruvbox magenta claro)
bright6=0FA17A   # Bright Cyan (Gradiente 4 profundo)
bright7=fbf1c7   # Bright White (crema claro)

[cursor]
color=282828 fe8019

# [2025-12-28 19:33:43.793] [error] Error calling StartServiceByName for org.freedesktop.portal.Desktop: Timeout was reached